apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce  # Allow only one node to write at a time
  resources:
    requests:
      storage: 1Gi  # Request 1GB of storage
