apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c2VjcmV0MTIz  # Base64 of "secret123"
  MYSQL_USER: dXNlcg==              # Base64 of "user"
  MYSQL_PASSWORD: cGFzc3dvcmQ=       # Base64 of "password"
